name: "Ensure packages build"
on:
  push:
    branches:
      - "mistress"
  pull_request:
    branches:
      - "mistress"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "build-pkg"
      - uses: "queer/actions/peckish_install@mistress"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build debug binary"
        run: "cargo build"
      - uses: "queer/actions/peckish_run@mistress"
